import Head from "next/head";
import Image from "next/image";
import React from "react";
import styled from "styled-components";
import { Instagram, KakaoTalk, Logo, Model, StringLogo } from "../assets/img";

function Header() {
  return (
    // <Head>
    //   <title>외딴썸</title>
    //   <meta name="description" content="Generated by create next app" />
    // </Head>
    <HeaderLayout>
      <HeaderTop>
        <a href="https://www.instagram.com/lonessum_official/">
          <Image
            src={Instagram}
            width={60}
            height={60}
            alt="외딴썸 공식 인스타그램"
          />
        </a>
        <a href="http://pf.kakao.com/_XUkxkb">
          <Image
            src={KakaoTalk}
            width={60}
            height={60}
            alt="외딴썸 공식 카카오톡"
          />
        </a>
      </HeaderTop>
      <Contents>
        <Description>
          <ImageWrapper>
            <Image src={Logo} width={102} height={102} alt="외딴썸 로고" />
          </ImageWrapper>
          <ImageWrapper>
            <Image
              src={StringLogo}
              width={213}
              height={71}
              alt="외딴썸 글자 로고"
            />
          </ImageWrapper>
          <ImageWrapper>
            유학생이 만든 국내 최초
            <br />
            유학생 미팅·소개팅 서비스
          </ImageWrapper>
          <GoAppLinkStyled>
            <a href="app.lonessum.com">매칭하러 가기</a>
          </GoAppLinkStyled>
        </Description>
        <Image src={Model} width={594} height={862} alt="모델 이미지" />
      </Contents>
    </HeaderLayout>
  );
}

const HeaderLayout = styled.header`
  background-color: #4adac4;
  padding: 30px 30px 0 30px;
  color: #ffff;
`;
const HeaderTop = styled.div`
  display: flex;
  justify-content: right;
  gap: 4px;
`;
export const Contents = styled.div`
  margin: 0 auto;
  display: flex;
  justify-content: center;
`;
export const Description = styled.article`
  width: 350px;
  margin-top: 140px;
`;
export const ImageWrapper = styled.div`
  margin: 20px 0;
  font-size: 24px;
`;
export const GoAppLinkStyled = styled.div`
  margin-top: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 300px;
  height: 68px;
  font-weight: 600;
  background-color: #ffff;
  color: #171717;
  border-radius: 50px;
  font-size: 30px;
  box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
`;
export default Header;
